parameters:

    #
    # Entities
    #
    elcodi.core.language.entity.locale.class: Elcodi\Component\Language\Entity\Locale

    #
    # Factories
    #
    elcodi.factory.language.class: Elcodi\Component\Language\Factory\LanguageFactory

    #
    # Services
    #
    elcodi.manager.language.class: Elcodi\Component\Language\Services\LanguageManager
    elcodi.manager.locale.class: Elcodi\Component\Language\Services\LocaleManager
    elcodi.provider.locale.class: Elcodi\Component\Language\Services\LocaleProvider

    #
    # Twig extensions
    #
    elcodi.twig_extension.language.class: Elcodi\Component\Language\Twig\LanguageExtension
