services:

    #
    # Factories
    #

    #
    # Factory for entity language
    #
    elcodi.factory.language:
        class: %elcodi.factory.language.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.language.entity.language.class%"]]
