services:

    #
    # Repositories
    #

    #
    # Repository for entity language
    #
    elcodi.repository.language:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.language.entity.language.class% ]
