services:

    #
    # Repositories
    #

    #
    # Repository for entity language
    #
    elcodi.core.language.repository.language:
        class: %elcodi.core.language.repository.language.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.language.entity.language.class%

    elcodi.repository.language:
        alias: elcodi.core.language.repository.language
