services:

    #
    # Providers
    #
    elcodi.core.language.service.locale_provider:
        class: %elcodi.core.language.service.locale_provider.class%
        arguments:
            request_stack: @request_stack
            default_locale: %locale%

    elcodi.locale_provider:
        alias: elcodi.core.language.service.locale_provider

    elcodi.locale_provider.locale:
        class: %elcodi.core.language.entity.locale.class%
        factory_service: elcodi.locale_provider
        factory_method: getLocale
        public: false

    #
    # Services
    #
    elcodi.core.language.service.language_manager:
        class: %elcodi.core.language.service.language_manager.class%
        arguments:
            language_repository: @elcodi.repository.language

    elcodi.language_manager:
        alias: elcodi.core.language.service.language_manager


    elcodi.core.language.service.locale_manager:
        class: %elcodi.core.language.service.locale_manager.class%
        arguments:
            locale: @elcodi.locale_provider.locale
        calls:
            - [initialize, []]

    elcodi.locale_manager:
        alias: elcodi.core.language.service.locale_manager

    #
    # Environment values
    #
    elcodi.languages:
        class: Doctrine\Common\Collections\Collection
        factory_service: elcodi.language_manager
        factory_method: getLanguages

    elcodi.languages_iso:
        class: Doctrine\Common\Collections\Collection
        factory_service: elcodi.language_manager
        factory_method: getLanguagesIso

    elcodi.languages_iso_array:
        class: stdClass
        factory_service: elcodi.languages_iso
        factory_method: toArray

    elcodi.locale:
        class: %elcodi.core.language.entity.locale.class%
        factory_service: elcodi.locale_manager
        factory_method: getLocale

    elcodi.locale_iso:
        class: stdClass
        factory_service: elcodi.locale_manager
        factory_method: getLocaleIso
