services:

    #
    # Providers
    #
    elcodi.core.language.service.locale_provider:
        class: %elcodi.core.language.service.locale_provider.class%
        arguments:
            request_stack: @request_stack
            default_locale: %locale%

    elcodi.locale_provider:
        alias: elcodi.core.language.service.locale_provider

    elcodi.locale_provider.locale:
        class: %elcodi.core.language.entity.locale.class%
        factory_service: elcodi.locale_provider
        factory_method: getLocale
        public: false

    #
    # Services
    #
    elcodi.core.language.service.language_manager:
        class: %elcodi.core.language.service.language_manager.class%
        arguments:
            language_repository: @elcodi.repository.language

    elcodi.language_manager:
        alias: elcodi.core.language.service.language_manager


    elcodi.core.language.service.locale_manager:
        class: %elcodi.core.language.service.locale_manager.class%
        arguments:
            locale: @elcodi.locale_provider.locale
        calls:
            - [initialize, []]

    elcodi.locale_manager:
        alias: elcodi.core.language.service.locale_manager

    elcodi.locale:
        class: %elcodi.core.language.entity.locale.class%
        factory_service: elcodi.locale_manager
        factory_method: getLocale
