services:

    #
    # Providers
    #
    elcodi.provider.locale:
        class: %elcodi.provider.locale.class%
        arguments:
            - @request_stack
            - %locale%

    elcodi.provider.locale.locale:
        class: %elcodi.entity.locale.class%
        factory_service: elcodi.provider.locale
        factory_method: getLocale
        public: false

    #
    # Services
    #
    elcodi.manager.language:
        class: %elcodi.manager.language.class%
        arguments:
            - @elcodi.repository.language

    elcodi.manager.locale:
        class: %elcodi.manager.locale.class%
        arguments:
            - @elcodi.provider.locale.locale
        calls:
            - [initialize, []]

    #
    # Environment values
    #
    elcodi.languages:
        class: Doctrine\Common\Collections\Collection
        factory_service: elcodi.manager.language
        factory_method: getLanguages

    elcodi.languages_iso:
        class: Doctrine\Common\Collections\Collection
        factory_service: elcodi.manager.language
        factory_method: getLanguagesIso

    elcodi.languages_iso_array:
        class: stdClass
        factory_service: elcodi.languages_iso
        factory_method: toArray

    elcodi.locale:
        class: %elcodi.entity.locale.class%
        factory_service: elcodi.manager.locale
        factory_method: getLocale
