services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.language:
        class: %elcodi.twig_extension.language.class%
        arguments:
            language_manager: @elcodi.manager.language
            master_language: @elcodi.locale_iso
        tags:
            - { name: twig.extension }
