services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.language:
        class: %elcodi.twig_extension.language.class%
        arguments:
            - @elcodi.manager.language
            - @elcodi.locale
        tags:
            - { name: twig.extension }
